### ISSUE TITLE
[BUG Report] Chrome 129.0.6668.100 横向滚动条消失

### ISSUE THREAD

**Issue by AnkioTomas** [baukh789/GridManager#307]
以官网demo为例：https://gridmanager.lovejavascript.com/demo/index.html#demo-fixedCode
![image](https://github.com/user-attachments/assets/af537f5b-74a7-4ea5-9d5d-c091acf42233)

**Comment by AnkioTomas** [comment]
```css
.table-div {
    /* scrollbar-width: thin; */
    /* scrollbar-color: #e1e1e1 #f3f3f3; */
}
```
研究发下是这两个属性导致的，Chrome最近更新了滚动条的默认行为。
如果使用上面这两个属性设置滚动条，默认情况下滚动条会自动隐藏，除非你进行了滚动行为。
```css
.table-div::-webkit-scrollbar-thumb {
    background-color: #f3f3f3;
    border-radius: 10px;
}
.table-div::-webkit-scrollbar {
    display: block;
    width: 12px;
}
```
加上这两行，强制显示滚动条
